In [1]:
import pandas as pd

In [2]:
df_input=pd.read_csv("./aoc_2003_prod.txt", header=None)

In [3]:
#df_input

In [4]:
df_pattern=df_input[0].str.split("", expand=True)
df_pattern=df_pattern.drop(columns=[0, len(df_pattern.columns)-1]).T.reset_index(drop=True).T

df_pattern

    0  1  2  3  4  5  6  7  8  9   ... 21 22 23 24 25 26 27 28 29 30
0    .  .  .  .  .  .  .  .  #  .  ...  .  .  .  #  .  .  .  .  .  #
1    .  .  .  .  .  .  .  .  .  .  ...  #  .  .  .  .  .  .  .  .  #
2    .  #  .  .  .  .  #  #  .  .  ...  .  .  .  .  .  .  .  .  .  .
3    .  #  .  .  .  .  .  .  .  #  ...  .  #  #  .  .  .  #  .  .  .
4    .  .  .  .  .  #  .  #  .  .  ...  .  .  .  .  .  #  .  .  .  .
..  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
318  .  .  .  .  .  .  .  .  .  .  ...  .  .  #  #  .  #  .  .  .  .
319  .  .  .  .  .  .  .  .  .  .  ...  .  .  .  #  .  .  .  #  .  .
320  .  #  .  .  .  .  .  .  .  .  ...  #  #  .  .  .  #  .  .  .  .
321  .  .  .  .  .  #  .  .  .  #  ...  #  .  #  #  .  .  .  .  .  .
322  #  .  .  .  #  .  .  #  .  #  ...  .  .  #  .  .  .  .  .  .  .

[323 rows x 31 columns]

In [5]:
xmax=len(df_pattern.columns)

In [6]:
paths1=[
    (3,1)
]

In [7]:
total=1
for stepX, stepY in paths1:
    x = 0
    result=0
    for y in range(0, len(df_pattern.index), stepY):
        result += int(df_pattern.iloc[y][x]=='#')
        x= (x+stepX) % xmax  
    total *= result
    print(f"For steps {stepX}, {stepY}: {result}, {total}")

For steps 3, 1: 153, 153

In [8]:
paths2=[
    (1,1), (3,1), (5,1), (7,1), (1,2)
]

In [9]:
total=1
for stepX, stepY in paths2:
    x = 0
    result=0
    for y in range(0, len(df_pattern.index), stepY):
        result += int(df_pattern.iloc[y][x]=='#')
        x= (x+stepX) % xmax  
    total *= result
    print(f"For steps {stepX}, {stepY}: {result}, {total}")

For steps 1, 1: 66, 66
For steps 3, 1: 153, 10098
For steps 5, 1: 79, 797742
For steps 7, 1: 92, 73392264
For steps 1, 2: 33, 2421944712